# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_doc", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "openprot_lib",
    srcs = [
        "src/lib.rs",
        "src/cli.rs",
        "src/commands/mod.rs",
        "src/commands/interact.rs",
        "src/transport/mctp_transport.rs",
        "src/transport/mod.rs",
        "src/transport/traits.rs",
    ],
    crate_name = "openprot",
    edition = "2024",
    deps = [
        "@rust_crates//:clap",
        "@rust_crates//:mctp",
        "//third_party/crates_io:mctp_lib",
    ],
)

rust_test(
    name = "openprot_test",
    crate = ":openprot_lib",
)

rust_binary(
    name = "openprot",
    srcs = ["src/main.rs"],
    edition = "2024",
    deps = [
        ":openprot_lib",
        "@rust_crates//:clap",
    ],
)

rust_doc(
    name = "openprot_lib_doc",
    crate = ":openprot_lib",
)

rust_doc(
    name = "openprot_doc",
    crate = ":openprot",
)
